In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/data/insurance.csv")

In [4]:
df.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
target = "charges"
y = df[target]
X = df.copy()
del X[target]
X = pd.get_dummies(X, drop_first=True)

X.head()

,age,bmi,children,gender_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,0,1,0,0,1
1,18,33.770,1,1,0,0,1,0
2,28,33.000,3,1,0,0,1,0
3,33,22.705,0,1,0,1,0,0
4,32,28.880,0,1,0,1,0,0

In [6]:
from sklearn import model_selection
from sklearn import preprocessing
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                                                , test_size = 0.3, random_state = 1)
scaler = preprocessing.StandardScaler()
scaler.fit(X_train) # it find mean and standard deviation of each column/feature
X_train_std = scaler.transform(X_train) # applies the mean and std to find Z-score
X_test_std = scaler.transform(X_test)

In [7]:
pd.DataFrame(X_train_std)

,0,1,2,3,4,5,6,7
0,0.797152,-0.702114,-0.904002,0.976766,-0.509664,1.788102,-0.600387,-0.587220
1,-1.271085,-0.703758,-0.085679,-1.023787,-0.509664,-0.559252,-0.600387,1.702939
2,-0.985811,-0.733340,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
3,0.797152,-0.414510,1.550967,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
4,0.868471,1.482037,-0.085679,0.976766,-0.509664,-0.559252,-0.600387,1.702939
5,-0.985811,1.749098,-0.904002,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
6,-0.843174,0.117970,-0.904002,-1.023787,1.962076,-0.559252,-0.600387,1.702939
7,1.724293,-0.608437,-0.904002,-1.023787,1.962076,1.788102,-0.600387,-0.587220
8,-1.485041,0.525546,-0.904002,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
9,-1.485041,-1.248563,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
10,1.367700,0.375170,-0.904002,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
11,-0.700537,-1.451529,-0.904002,-1.023787,1.962076,-0.559252,-0.600387,-0.587220
12,0.012648,1.827162,-0.904002,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
13,1.153745,0.749878,-0.085679,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
14,-0.343944,-0.522978,-0.085679,-1.023787,-0.509664,-0.559252,-0.600387,1.702939
15,-1.342404,-1.426878,-0.085679,0.976766,-0.509664,-0.559252,-0.600387,1.702939
16,1.581656,-1.576432,-0.904002,-1.023787,-0.509664,1.788102,-0.600387,-0.587220
17,-1.342404,-0.452309,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
18,-0.629218,1.339056,-0.085679,0.976766,-0.509664,-0.559252,1.665591,-0.587220
19,0.725834,1.013652,-0.904002,0.976766,-0.509664,-0.559252,1.665591,-0.587220
20,-0.914493,-0.311794,-0.904002,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
21,-0.843174,0.676744,-0.085679,-1.023787,-0.509664,-0.559252,-0.600387,1.702939
22,-0.201307,-0.125262,-0.904002,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
23,-1.342404,-1.029162,-0.904002,-1.023787,1.962076,-0.559252,1.665591,-0.587220
24,-1.413722,-1.788438,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,1.702939
25,-1.485041,-0.858242,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
26,1.082426,0.843555,1.550967,-1.023787,-0.509664,1.788102,-0.600387,-0.587220
27,-1.413722,0.297106,-0.904002,-1.023787,1.962076,1.788102,-0.600387,-0.587220
28,0.297922,-1.734204,0.732644,0.976766,1.962076,-0.559252,1.665591,-0.587220
29,-1.199767,0.507468,-0.904002,0.976766,-0.509664,-0.559252,1.665591,-0.587220
...,...,...,...,...,...,...,...,...
906,1.153745,0.742482,-0.904002,-1.023787,1.962076,-0.559252,1.665591,-0.587220
907,-0.914493,0.297106,-0.085679,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
908,1.082426,0.265881,-0.085679,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
909,1.367700,-1.300332,-0.904002,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
910,-1.057130,0.331619,-0.904002,0.976766,1.962076,-0.559252,-0.600387,1.702939
911,-0.985811,1.881396,-0.085679,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
912,1.439019,-0.858242,-0.085679,0.976766,-0.509664,-0.559252,-0.600387,-0.587220
913,-0.843174,-0.029941,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,1.702939
914,1.795612,-0.835234,0.732644,0.976766,-0.509664,-0.559252,-0.600387,1.702939
915,1.652975,0.219042,-0.904002,0.976766,1.962076,-0.559252,-0.600387,-0.587220
916,1.082426,0.579780,0.732644,0.976766,1.962076,-0.559252,1.665591,-0.587220
917,0.369241,0.272454,-0.085679,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
918,-0.771855,-1.045596,-0.085679,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
919,-0.415263,-0.998758,0.732644,0.976766,-0.509664,1.788102,-0.600387,-0.587220
920,0.583197,-0.140053,1.550967,0.976766,-0.509664,1.788102,-0.600387,-0.587220
921,0.012648,-0.124440,-0.085679,0.976766,1.962076,-0.559252,-0.600387,-0.587220
922,0.440560,-0.052950,-0.904002,0.976766,1.962076,-0.559252,1.665591,-0.587220
923,-1.199767,0.234655,-0.904002,0.976766,-0.509664,1.788102,-0.600387,-0.587220
924,-1.057130,-0.486822,-0.904002,-1.023787,-0.509664,-0.559252,1.665591,-0.587220
925,-1.057130,-0.889468,-0.904002,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
926,-0.771855,0.031688,-0.904002,0.976766,-0.509664,1.788102,-0.600387,-0.587220
927,-0.058670,0.660310,0.732644,0.976766,-0.509664,-0.559252,-0.600387,1.702939
928,-0.629218,-0.327407,1.550967,0.976766,1.962076,1.788102,-0.600387,-0.587220
929,-1.413722,1.468068,-0.085679,-1.023787,-0.509664,1.788102,-0.600387,-0.587220
930,-1.128448,3.237246,-0.085679,0.976766,-0.509664,-0.559252,1.665591,-0.587220
931,1.510338,-0.292894,-0.904002,0.976766,-0.509664,-0.559252,-0.600387,1.702939
932,-0.914493,-0.218117,0.732644,-1.023787,-0.509664,-0.559252,-0.600387,-0.587220
933,0.868471,0.703039,0.732644,-1.023787,1.962076,-0.559252,-0.600387,-0.587220
934,0.083967,-1.390722,0.732644,-1.023787,1.962076,-0.559252,1.665591,-0.587220
935,1.296382,-0.450666,-0.085679,0.976766,-0.509664,-0.559252,1.665591,-0.587220

In [8]:
import numpy as np

In [9]:
np.random.seed(100)
a = np.random.ranf(10)
a

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [10]:
a

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [11]:
from sklearn import linear_model

In [12]:
est = linear_model.LinearRegression()
est.fit(X_train_std, y_train)

/Users/abulbasar/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
y_train_pred = est.predict(X_train_std )

In [14]:
y_test_pred = est.predict(X_test_std)

In [15]:
sse = np.sum((y_train_pred - y_train) ** 2) # sum of squared error

In [16]:
sse

34142276155.204025

In [17]:
mse_train = sse/len(X_train)

In [18]:
pd.DataFrame({"actual": y_train, "pred": y_train_pred})

           actual          pred
744    8827.20990   9472.264706
363    2597.77900   2233.928867
10     2721.32080   3423.054245
970   10702.64240  10718.882756
634    9391.34600  13789.363595
554   17878.90068   8575.538050
314   34838.87300  29070.391813
419   28950.46920  37270.077567
525   11482.63485   3474.235997
1041   1704.70015    650.591339
649   12430.95335  14185.866667
1306  16115.30450  27363.128132
790    5662.22500  11312.876891
1044  11394.06555  14228.036144
104    5003.85300   5860.421131
1295   1964.78000    280.938585
370   13415.03810  10808.451521
495    1967.02270   2715.930292
1162  18963.17192   8152.412366
903    8125.78450  11951.073117
125    3385.39915   4784.460516
694    3577.99900   6452.088555
979    4889.03680   6727.848706
1223  26125.67477  24987.189253
1251   1241.56500  -1024.963571
529    1708.00140   1416.265468
1018  12495.29085  14828.750829
1139  36898.73308  27972.439480
1011  18767.73770  29799.955047
1097   1674.63230   4162.704309
...           ...           ...
1031  44423.80300  37271.409105
141    3490.54910   6041.080065
1110  11512.40500  13309.714705
753   11833.78230   9959.767626
1001  34472.84100  28451.655710
1239   3238.43570   8240.683440
580   12913.99240  12080.186194
562    2494.02200   4438.054794
398   14988.43200  12860.505691
668   45710.20785  38662.918606
252   44260.74990  37107.694188
907    7633.72060   9866.449521
468   23288.92840   4193.321139
914    5257.50795   5301.689171
357    9620.33070  10854.682622
1278  22462.04375  32545.406730
1300  62592.87309  32911.430830
1202   2055.32490   4262.790391
1305   2464.61880   2998.410290
508    3044.21330   3147.899075
749    3062.50825   5374.731035
129    6082.40500   9250.518070
144   20745.98910  30267.957810
960    2730.10785   6555.035644
847    2438.05520  10114.233494
715   12146.97100  12227.733773
905    4564.19145   5658.150817
1096  44641.19740  37816.578866
235   19444.26580  30001.499032
1061  11554.22360  11437.005352

[936 rows x 2 columns]

In [19]:
sse = np.sum((y_test_pred - y_test) ** 2) # sum of squared error
sse

14778105453.509338

In [20]:
mse_test = sse/len(X_test)

In [21]:
mse_test/mse_train

1.0078040195407358

In [22]:
y_train_mean = np.mean(y_train)

In [23]:
sst = np.sum((y_train_mean - y_test) ** 2)

In [24]:
sse/sst

0.25940026954889744

In [25]:
r2 = 1 - sse/sst
r2

0.7405997304511025

In [26]:
est

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [27]:
est.intercept_

13276.698553898505

In [28]:
est.coef_

array([3528.98273114, 1961.65520818,  421.55016415, -141.35911014,
       9733.78688309, -129.54588605, -414.54148288, -379.09534369])

In [29]:
pd.DataFrame({"feature": X.columns, "coef": est.coef_})

          coef           feature
0  3528.982731               age
1  1961.655208               bmi
2   421.550164          children
3  -141.359110       gender_male
4  9733.786883        smoker_yes
5  -129.545886  region_northwest
6  -414.541483  region_southeast
7  -379.095344  region_southwest

In [31]:
df.groupby("gender").charges.mean()

gender
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [32]:
from sklearn import *

/Users/abulbasar/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/abulbasar/anaconda3/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
/Users/abulbasar/anaconda3/lib/python3.6/site-packages/sklearn/learning_curve.py:22: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)

In [35]:
target = "charges"
y = df[target]
X = df.copy()
del X[target]
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                                , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)
print(
    "training MSE", metrics.mean_squared_error(y_train, y_train_pred),
    "\ntesting MSE", metrics.mean_squared_error(y_test, y_test_pred),
    "\ntraining R2", metrics.r2_score(y_train, y_train_pred),
    "\ntesting R2", metrics.r2_score(y_test, y_test_pred)
     )

training MSE 36476790.76410686
testing MSE 36761456.35201328
training R2 0.7545557492633161
testing R2 0.740598931692721

In [36]:
target = "charges"
y = np.log(df[target])
X = df.copy()
del X[target]
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                                , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)
print(
    "training MSE", metrics.mean_squared_error(y_train, y_train_pred),
    "\ntesting MSE", metrics.mean_squared_error(y_test, y_test_pred),
    "\ntraining R2", metrics.r2_score(y_train, y_train_pred),
    "\ntesting R2", metrics.r2_score(y_test, y_test_pred)
     )

training MSE 0.20407164987815388
testing MSE 0.17881132833282085
training R2 0.7589104330619343
testing R2 0.78742951961976

In [39]:
target = "charges"
y = np.log(df[target])
X = df.copy()

def find_bmi_cat(bmi):
    if bmi > 30:
        return "high"
    elif bmi > 20: 
        return "normal"
    else:
        return "low"

def age_group(age):
    if age > 60: 
        return "senior"
    elif age > 30:
        return "middle age"
    else:
        return "young"
    
X["bmi_cat"] = X.bmi.apply(find_bmi_cat)
X["age_group"] = X.age.apply(age_group)

del X[target]
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                                , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)
print(
    "training MSE", metrics.mean_squared_error(y_train, y_train_pred),
    "\ntesting MSE", metrics.mean_squared_error(y_test, y_test_pred),
    "\ntraining R2", metrics.r2_score(y_train, y_train_pred),
    "\ntesting R2", metrics.r2_score(y_test, y_test_pred)
     )

training MSE 0.202172049386348
testing MSE 0.1767987318378707
training R2 0.7611546147510531
testing R2 0.7898220895297986

In [41]:
target = "charges"
y = np.log(df[target])
X = df.copy()

def find_bmi_cat(bmi):
    if bmi > 30:
        return "high"
    elif bmi > 20: 
        return "normal"
    else:
        return "low"

def age_group(age):
    if age > 60: 
        return "senior"
    elif age > 30:
        return "middle age"
    else:
        return "young"
    
X["bmi_cat"] = X.bmi.apply(find_bmi_cat)
X["age_group"] = X.age.apply(age_group)
#X["bmi2"] = X.bmi ** 2

del X[target]
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                                , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=2, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)
print(
    "training MSE", metrics.mean_squared_error(y_train, y_train_pred),
    "\ntesting MSE", metrics.mean_squared_error(y_test, y_test_pred),
    "\ntraining R2", metrics.r2_score(y_train, y_train_pred),
    "\ntesting R2", metrics.r2_score(y_test, y_test_pred)
     )

training MSE 0.135070027027061
testing MSE 0.10996343346544231
training R2 0.8404287202964738
testing R2 0.869275732729294

In [51]:
X.shape

(1338, 12)

In [56]:
a = (np.random.ranf([4, 200]) * 10).astype(np.int32)

In [57]:
a

array([[5, 9, 3, 3, 8, 7, 3, 6, 5, 2, 1, 3, 4, 6, 2, 6, 2, 6, 7, 7, 6, 3,
        6, 8, 6, 9, 9, 1, 0, 1, 9, 9, 2, 3, 5, 2, 4, 6, 5, 7, 5, 0, 3, 4,
        4, 3, 5, 4, 0, 2, 9, 0, 0, 2, 5, 9, 9, 9, 1, 6, 5, 1, 9, 2, 9, 5,
        1, 3, 1, 4, 5, 7, 4, 3, 5, 4, 3, 3, 2, 4, 4, 8, 7, 7, 3, 3, 6, 7,
        1, 1, 4, 1, 9, 8, 5, 2, 1, 9, 7, 8, 3, 2, 2, 8, 4, 6, 8, 2, 0, 7,
        9, 9, 4, 6, 7, 9, 1, 4, 4, 6, 4, 8, 8, 0, 3, 9, 0, 4, 9, 8, 2, 5,
        4, 5, 8, 5, 4, 3, 2, 5, 0, 6, 7, 9, 6, 4, 4, 9, 2, 4, 9, 0, 7, 0,
        3, 0, 0, 1, 1, 6, 4, 8, 2, 1, 7, 8, 5, 7, 6, 5, 8, 9, 8, 2, 8, 4,
        7, 4, 1, 7, 2, 8, 8, 5, 3, 5, 1, 8, 9, 7, 2, 8, 8, 0, 2, 5, 1, 6,
        9, 2],
       [7, 0, 3, 9, 6, 6, 9, 1, 0, 1, 5, 4, 8, 8, 2, 4, 4, 0, 0, 7, 2, 7,
        4, 1, 1, 3, 8, 0, 0, 5, 6, 7, 4, 3, 8, 4, 3, 0, 0, 0, 6, 6, 2, 6,
        0, 8, 1, 1, 4, 7, 8, 2, 0, 7, 5, 7, 9, 4, 4, 5, 5, 5, 3, 5, 9, 9,
        3, 7, 6, 2, 0, 0, 1, 2, 8, 2, 7, 5, 1, 7, 9, 9, 7, 6, 5, 3, 9, 0,
        8, 2, 5, 5, 5, 6, 1, 2, 1, 0, 9, 3, 1, 3, 3, 6, 2, 6, 0, 5, 1, 5,
        5, 2, 4, 0, 5, 0, 5, 5, 0, 9, 6, 6, 4, 7, 1, 6, 5, 9, 7, 5, 4, 7,
        8, 9, 8, 0, 7, 5, 8, 4, 5, 9, 5, 1, 6, 0, 3, 8, 5, 1, 3, 9, 0, 7,
        1, 2, 6, 1, 3, 4, 6, 5, 4, 5, 8, 8, 1, 9, 0, 9, 1, 0, 7, 9, 7, 6,
        1, 1, 1, 0, 9, 5, 4, 3, 4, 1, 1, 8, 2, 0, 3, 8, 4, 7, 9, 0, 1, 6,
        8, 4],
       [0, 0, 1, 2, 8, 9, 1, 8, 7, 6, 8, 2, 5, 3, 6, 2, 5, 3, 5, 1, 5, 4,
        1, 5, 2, 6, 5, 2, 5, 3, 8, 4, 1, 9, 8, 2, 2, 0, 3, 0, 9, 7, 5, 3,
        1, 4, 2, 9, 0, 4, 0, 5, 5, 1, 6, 1, 5, 3, 2, 1, 1, 0, 4, 7, 8, 6,
        3, 6, 3, 7, 9, 0, 6, 3, 7, 9, 2, 0, 6, 0, 6, 6, 0, 3, 4, 0, 3, 5,
        0, 1, 8, 3, 3, 5, 5, 8, 2, 2, 3, 1, 2, 7, 3, 2, 9, 9, 3, 4, 8, 0,
        5, 8, 7, 8, 0, 6, 9, 7, 4, 2, 9, 4, 7, 6, 8, 9, 4, 1, 5, 9, 4, 8,
        4, 8, 2, 4, 7, 6, 7, 9, 3, 8, 2, 0, 2, 7, 3, 5, 2, 4, 1, 3, 8, 8,
        9, 4, 9, 4, 8, 4, 3, 6, 7, 7, 6, 8, 6, 2, 8, 1, 5, 3, 6, 5, 4, 8,
        4, 6, 5, 5, 6, 9, 2, 7, 9, 5, 8, 6, 3, 8, 2, 9, 9, 6, 5, 2, 4, 7,
        2, 2],
       [3, 5, 4, 5, 4, 7, 3, 7, 8, 1, 6, 5, 9, 0, 7, 2, 9, 3, 0, 9, 4, 4,
        5, 9, 4, 0, 9, 7, 7, 1, 7, 7, 9, 5, 7, 8, 4, 4, 1, 1, 5, 2, 1, 5,
        9, 2, 7, 7, 7, 9, 3, 6, 1, 7, 4, 4, 6, 4, 7, 5, 8, 3, 6, 3, 6, 3,
        0, 4, 7, 2, 6, 1, 6, 0, 0, 5, 2, 3, 6, 9, 5, 7, 5, 3, 6, 2, 8, 2,
        1, 4, 2, 2, 6, 4, 9, 7, 3, 7, 2, 2, 6, 4, 1, 3, 0, 3, 8, 9, 6, 1,
        5, 3, 5, 5, 4, 7, 8, 8, 9, 9, 1, 1, 9, 0, 8, 4, 2, 7, 4, 3, 0, 8,
        4, 7, 3, 2, 7, 8, 7, 0, 3, 0, 9, 1, 3, 3, 2, 1, 7, 9, 6, 1, 7, 6,
        0, 4, 3, 4, 1, 5, 6, 8, 7, 0, 7, 6, 6, 0, 0, 1, 2, 0, 2, 2, 8, 2,
        8, 2, 0, 7, 5, 5, 3, 5, 8, 1, 2, 7, 2, 5, 3, 0, 4, 7, 9, 3, 4, 5,
        5, 1]], dtype=int32)

In [58]:
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(a).shape

(4, 20300)